default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  # kindly replace your database user access
  username: postgres
  # kindly replace your database password
  password: Temitope2604

development:
  <<: *default
  database:  BudgetAppV_development

test:
  <<: *default
  database:  BudgetAppV_test

production:
  <<: *default
  database: BudgetAppV_production
  username: BudgetAppV
  password: <%= ENV["BUDGETAPP_DATABASE_PASSWORD"] %>
