default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  # kindly replace your database user access
  username: postgres
  # kindly replace your database password
  password: Temitope2604

development:
  <<: *default
  database:  BudgetApp8_development

test:
  <<: *default
  database:  BudgetApp8_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>